<a href="https://colab.research.google.com/github/SlavenDerickPais/ML-lab-2547249/blob/Lab03/Lab03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import pandas as pd
import numpy as np

In [10]:
data= pd.read_csv("/content/drive/MyDrive/MACHINE LEARNING/Student Awareness Survey (Responses) - Form Responses 1.csv")

In [11]:
data.head(5)

,Timestamp,Registration Number,Email,Job role that you are interested in,What is the minimum salary of students placed through campus (In LPA..respond as a number),What is the maximum salary of students placed through campus (In LPA..respond as a number),What is the median salary of students placed through campus (In LPA..respond as a number),Which is the highest paying company that recruits from campus?,Rate your contribution towards extra curricular activities,Rate your technical competencies,What are your package expectations (LPA),Your CIA % of last semester,Your GPA of last semester,Your maximum attendance % till last semester,Internships Interests
0,6/15/2026 9:25:39,2547231,kunnal.kunnal@mca.christuniversity.in,Software Development Engineer (SDE),3.5,12,6.8,Akasa air,4.0,3.0,8,69,3.40,98,"AI/ML, Web Development, Data Science/Analytics..."
1,6/15/2026 9:53:54,2547237,omkaar.chakraborty@mca.christuniversity.in,Software Development Engineer (SDE),6,20,10,Fractal,4.0,4.0,12,75,3.69,95,"Web Development, DevOps/Cloud Computing, Mobil..."
2,6/15/2026 9:54:56,2547203,abhinav.jain@mca.christuniversity.in,Full Stack Developer,4,12,6.3,Akasa Air,5.0,4.0,12,82,3.41,95,"AI/ML, Web Development, Mobile App Development"
3,6/15/2026 9:55:17,2547228,jai.pareek@mca.christuniversity.in,Full Stack Developer,600000,1400000,800000,Akasa airlines,5.0,4.0,1200000,91,3.60,92,"Web Development, DevOps/Cloud Computing, Cyber..."
4,6/15/2026 9:55:42,2547241,r.karan@mca.christuniversity.in,Software Development Engineer (SDE),4,4,6,12,2.0,3.0,12,70,3.54,93,"AI/ML, Data Science/Analytics"

In [12]:
data = data.drop(columns=['Timestamp','Email','Job role that you are interested in','What is the minimum salary of students placed through campus (In LPA..respond as a number)','What is the maximum salary of students placed through campus (In LPA..respond as a number)','What is the median salary of students placed through campus (In LPA..respond as a number)','Which is the highest paying company that recruits from campus?','Rate your contribution towards extra curricular activities','Rate your technical competencies','What are your package expectations (LPA)','Internships Interests'])

In [13]:
data

,Registration Number,Your CIA % of last semester,Your GPA of last semester,Your maximum attendance % till last semester
0,2547231,69,3.40,98
1,2547237,75,3.69,95
2,2547203,82,3.41,95
3,2547228,91,3.60,92
4,2547241,70,3.54,93
5,2547233,75,3.67,98
6,2547213,74,3.40,94
7,2547240,68,3.40,85
8,2547229,73,3.60,90
9,2547234,79,3.73,93
10,2547242,72,3.54,95
11,2547224,80,3.00,95
12,2547243,78,3.32,95
13,2547247,7,8.00,85%
14,2547249,70,3.49,100
15,2547226,60,3.00,85
16,2547239,68,3.14,88
17,2547220,71 %,3.40,91 %
18,2547222,64,3.11,100
19,2547209,71.78,3.49,96.54
20,2547216,70,3.34,95
21,2547256,63,3.40,90
22,2547250,76%,3.69,95%
23,2547245,83%,3.90,98%
24,2547257,80%,3.37,94.70%
25,2547255,72,3.55,93
26,2547223,70,3.40,96
27,2547232,70,3.00,93
28,2547262,71,3.33,99
29,2547244,77,3.30,90
30,2547210,80,3.79,100
31,2547218,80,3.12,92
32,2547221,80%,3.60,95%
33,2547208,70,3.40,94
34,2547211,85%,3.14,89%
35,2547261,71,3.40,88
36,2547236,68,3.40,97
37,2547201,67,3.46,95
38,2547204,72,3.40,100
39,2547205,65 %,3.30,89%
40,2547206,76,3.60,96
41,2547246,75.2,3.54,96
42,2547212,69.78,3.30,92
43,2547259,71.11%,3.37,93%
44,2547230,79.56,3.60,95
45,2547252,75,3.66,95
46,2547254,70,3.69,97
47,2547260,62%,3.00,97%
48,2547217,66%,2.74,90
49,2547238,63,3.13,94

In [14]:
data =data.rename(columns={"Your CIA % of last semester":"CIA","Your GPA of last semester":"GPA","Your maximum attendance % till last semester":"Attendance"})

In [15]:
data.head(5)

   Registration Number CIA   GPA Attendance
0              2547231  69  3.40         98
1              2547237  75  3.69         95
2              2547203  82  3.41         95
3              2547228  91  3.60         92
4              2547241  70  3.54         93

In [17]:
data.shape

(50, 4)

In [19]:
data.isnull().sum()

Registration Number    0
CIA                    0
GPA                    0
Attendance             0
dtype: int64

In [21]:
data.dtypes

Registration Number      int64
CIA                     object
GPA                    float64
Attendance              object
dtype: object

In [26]:
data["CIA"] = data["CIA"].str.replace("%","")
data["Attendance"] = data["Attendance"].str.replace("%","")

In [27]:
data['CIA'] = pd.to_numeric(data['CIA'], errors='coerce')
data['Attendance'] = pd.to_numeric(data['Attendance'], errors='coerce')
data['GPA'] = pd.to_numeric(data['GPA'], errors='coerce')

In [28]:
print("Duplicates:", data.duplicated().sum())

Duplicates: 0

In [30]:
data = data[(data['CIA'] >= 0) & (data['CIA'] <= 100)]

In [31]:
data = data[(data['Attendance'] >= 0) & (data['Attendance'] <= 100)]

In [32]:
data = data[(data['GPA'] >= 0) & (data['GPA'] <= 10)]

In [34]:
Q1 = data['CIA'].quantile(0.25)
Q3 = data['CIA'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

cia_outliers = data[(data['CIA'] < lower) | (data['CIA'] > upper)]

print("CIA Outliers:")
print(cia_outliers)

CIA Outliers:
    Registration Number   CIA  GPA  Attendance
3               2547228  91.0  3.6        92.0
13              2547247   7.0  8.0        85.0

In [35]:
Q1 = data['Attendance'].quantile(0.25)
Q3 = data['Attendance'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

attendance_outliers = data[(data['Attendance'] < lower) | (data['Attendance'] > upper)]

print("Attendance Outliers:")
print(attendance_outliers)

Attendance Outliers:
    Registration Number   CIA  GPA  Attendance
7               2547240  68.0  3.4        85.0
13              2547247   7.0  8.0        85.0
15              2547226  60.0  3.0        85.0

In [36]:
Q1 = data['GPA'].quantile(0.25)
Q3 = data['GPA'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

gpa_outliers = data[(data['GPA'] < lower) | (data['GPA'] > upper)]

print("GPA Outliers:")
print(gpa_outliers)

GPA Outliers:
    Registration Number   CIA   GPA  Attendance
13              2547247   7.0  8.00        85.0
48              2547217  66.0  2.74        90.0

In [37]:
data.loc[data['CIA'] == 7, 'CIA'] = 70